// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24.03.2026 04:07:55
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/umut/Desktop/ccc - Kopya/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/ccc - Kopya/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/ccc - Kopya/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/ccc - Kopya/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/ccc - Kopya/app/plugins/**/*.{js,ts,mjs}","C:/Users/umut/Desktop/ccc - Kopya/app/composables/**/*.{js,ts,mjs}","C:/Users/umut/Desktop/ccc - Kopya/app/utils/**/*.{js,ts,mjs}","C:/Users/umut/Desktop/ccc - Kopya/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/ccc - Kopya/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/ccc - Kopya/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/ccc - Kopya/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;