// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25.03.2026 00:43:45
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/umut/Desktop/vize acentası/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/vize acentası/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/vize acentası/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/vize acentası/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/vize acentası/app/plugins/**/*.{js,ts,mjs}","C:/Users/umut/Desktop/vize acentası/app/composables/**/*.{js,ts,mjs}","C:/Users/umut/Desktop/vize acentası/app/utils/**/*.{js,ts,mjs}","C:/Users/umut/Desktop/vize acentası/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/vize acentası/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/vize acentası/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/umut/Desktop/vize acentası/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;